### ISSUE TITLE
生成图片报错

### ISSUE THREAD

**Issue by Origin1699** [pcrbot/image-generate#2]
```
[2020-09-06 15:18:27,908 image-generate] INFO: Message 805 triggered generate_img by PrefixTrigger.
[2020-09-06 15:18:27,940 image-generate] ERROR: <class 'OSError'> occured when generate_img handling message 805.
[2020-09-06 15:18:27,947 image-generate] ERROR: cannot open resource
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/image-generate/__init__.py", line 21, in generate_img
    await main.img(bot, ev, msg, uid)
  File "/root/HoshinoBot/hoshino/modules/image-generate/main.py", line 24, in img
    ttfront = ImageFont.truetype('simhei.ttf',font_size)  # 设置字体暨字号
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by xhl6666** [comment]
README.md>开始使用>5.如果出现字体缺失的情况,请自行安装目录下ttf格式的字体

**Comment by xhl6666** [comment]
linux的话可以把字体文件丢在/usr/share/fonts/truetype/simhei/里面
